Repository Nitrokey/nitrokey-app2, pull requests merged in 2023-11, with the labels that each got.

#163 Fix missing UI resource files
  .github/workflows/cd-pypi.yaml
  Makefile
Labels: cicd

#167 Add libglib2.0 for libgthread
  .github/workflows/cd-pypi.yaml
Labels: bug, cicd

#168 fix timeout UI OTP
  nitrokeyapp/secrets_tab/__init__.py
Labels: ui
