Repository Nitrokey/nitrokey-app2, pull requests merged in 2024-01, with the labels that each got.

#193 Change PyPI repository url
  .github/workflows/cd-pypi.yaml
Labels: bug, cicd

#194 Build RPM package
  Makefile
  ci-scripts/linux/rpm/icons/hicolor/128x128/apps/nitrokey-app2.png
  ci-scripts/linux/rpm/icons/hicolor/16x16/apps/nitrokey-app2.png
  ci-scripts/linux/rpm/icons/hicolor/22x22/apps/nitrokey-app2.png
  ci-scripts/linux/rpm/icons/hicolor/24x24/apps/nitrokey-app2.png
  ci-scripts/linux/rpm/icons/hicolor/32x32/apps/nitrokey-app2.png
  ci-scripts/linux/rpm/icons/hicolor/48x48/apps/nitrokey-app2.png
  ci-scripts/linux/rpm/icons/hicolor/scalable/apps/nitrokey-app2.svg
  ci-scripts/linux/rpm/nitrokey-app2.desktop
  ci-scripts/linux/rpm/nitrokey-app2.spec
Labels: feature, cicd

#180 fix check for app update
  nitrokeyapp/welcome_tab.py
Labels: bug

#201 Raise version of pynitrokey dependency
  poetry.lock
  pyproject.toml
Labels: dependencies
